LoRinoBackend/Controllers/EventTagController.cs
using LoRinoBackend.Hubs; // Provides hub functionality for SignalR
using LoRinoBackend.Models; // Contains models used in the application
using Microsoft.AspNetCore.Identity; // Provides classes for identity management
using Microsoft.AspNetCore.Mvc; // Provides classes for MVC controller base
using Microsoft.AspNetCore.Mvc.Rendering; // Provides classes for rendering HTML in MVC views
using Microsoft.AspNetCore.SignalR; // Provides classes for SignalR hubs
using System; // Provides base classes and fundamental types
using System.Collections.Generic; // Provides generic collection types
using System.Linq; // Provides LINQ functionality

namespace LoRinoBackend.Controllers
{
    // Controller responsible for managing event tags
    public class EventTagController : Controller
    {
        // Dependencies injected through the constructor
        private readonly IMoveeDataRepository _moveeDataRepository; // Repository for Movee data
        private readonly IMoveeEventRepository _moveeEventRepository; // Repository for Movee events
        private readonly IMoveeEventTagRepository _moveeEventTagRepository; // Repository for Movee event tags
        private readonly IDeviceRepository _deviceRepository; // Repository for devices
        private readonly ILocationRepository _locationRepository; // Repository for locations
        private readonly IAlarmSoundRepository _alarmSoundRepository; // Repository for alarm sounds
        private readonly UserManager<ApplicationUser> _userManager; // Manager for user-related functionality

        // Constructor to initialize dependencies
        public EventTagController(IHubContext<WanesyHub> hubContext,
                                  IMoveeDataRepository moveeDataRepository,
                                  IMoveeEventRepository moveeEventRepository,
                                  IMoveeEventTagRepository moveeEventTagRepository,
                                  IDeviceRepository deviceRepository,
                                  UserManager<ApplicationUser> userManager,
                                  ILocationRepository locationRepository,
                                  IAlarmSoundRepository alarmSoundRepository)
        {
            _moveeDataRepository = moveeDataRepository;
            _moveeEventRepository = moveeEventRepository;
            _moveeEventTagRepository = moveeEventTagRepository;
            _deviceRepository = deviceRepository;
            _userManager = userManager;
            _locationRepository = locationRepository;
            _alarmSoundRepository = alarmSoundRepository;
        }

        // Returns a JSON response with error details
        public IActionResult returnError(int errorCode, string errorData)
        {
            return Json(new ReturnError { ErrorCode = errorCode, ErrorDescription = errorData });
        }

        // Displays a list of event tags associated with a specific event
        public IActionResult Index(int eventId)
        {
            var currentUserId = _userManager.GetUserId(HttpContext.User); // Gets the current user's ID
            // Activates alarm sound for the current user
            ViewBag.Alarm = _alarmSoundRepository.ActivateSoundAlarm(currentUserId);

            // Retrieves event tags for the given event ID
            string eId = HttpContext.Request.Query["eventId"].ToString(); // Retrieves the event ID from the query string
            var eventTags = (from et in _moveeEventTagRepository.GetAllMoveeEventTags() // Retrieves all event tags
                             where et.MoveeEventFrameId == eventId // Filters tags by the specified event ID
                             select new MoveeEventTag // Selects relevant properties for the view
                             {
                                 Id = et.Id,
                                 MoveeEventFrameId = et.MoveeEventFrameId,
                                 MoveeTagId = et.MoveeTagId,
                                 TagName = (from u in _moveeEventTagRepository.GetMoveeTags() where u.Id == et.MoveeTagId select u.Name).FirstOrDefault()
                             }).ToList();

            ViewBag.EventId = eId; // Sets the event ID in the ViewBag for use in the view
            return View(eventTags); // Returns the view with the list of event tags
        }

        // Displays the view for creating a new event tag
        public IActionResult Create(int eventId)
        {
            var currentUserId = _userManager.GetUserId(HttpContext.User); // Gets the current user's ID
            // Activates alarm sound for the current user
            ViewBag.Alarm = _alarmSoundRepository.ActivateSoundAlarm(currentUserId);
            ViewBag.EventId = HttpContext.Request.Query["eventId"].ToString(); // Sets the event ID in the ViewBag
            ViewBag.Tags = GetTags(); // Retrieves a list of tags for selection
            return View(); // Returns the view for creating a new event tag
        }

        // Handles the POST request to create a new event tag
        [HttpPost]
        [ActionName("Create")] // Specifies that this method handles the "Create" action
        public IActionResult Create(MoveeEventTag moveeEventTag)
        {
            var userId = _userManager.GetUserId(HttpContext.User); // Gets the current user's ID
            DateTimeOffset now = DateTimeOffset.UtcNow; // Gets the current UTC time
            long unixTimeMilliseconds = now.ToUnixTimeMilliseconds(); // Converts the current time to Unix time in milliseconds

            if (ModelState.IsValid) // Checks if the model state is valid
            {
                ViewBag.EventId = moveeEventTag.MoveeEventFrameId; // Sets the event ID in the ViewBag
                _moveeEventTagRepository.CreateMoveeEventTag(moveeEventTag, userId, unixTimeMilliseconds); // Creates the event tag
                return RedirectToAction(nameof(Index), new { eventId = moveeEventTag.MoveeEventFrameId }); // Redirects to the index action with the event ID
            }
            return View(moveeEventTag); // Returns the view with the model if the model state is invalid
        }

        // Displays the view for editing an existing event tag
        public IActionResult Edit(int id)
        {
            var currentUserId = _userManager.GetUserId(HttpContext.User); // Gets the current user's ID
            // Activates alarm sound for the current user
            ViewBag.Alarm = _alarmSoundRepository.ActivateSoundAlarm(currentUserId);
            var eventTag = _moveeEventTagRepository.GetMoveeEventTagById(id); // Retrieves the event tag by ID

            ViewBag.Tags = GetTags(); // Retrieves a list of tags for selection
            return View(eventTag); // Returns the view for editing the event tag
        }

        // Handles the POST request to update an existing event tag
        [HttpPost]
        public IActionResult Edit(MoveeEventTag eventTag)
        {
            if (ModelState.IsValid) // Checks if the model state is valid
            {
                _moveeEventTagRepository.UpdateMoveeEventTag(eventTag); // Updates the event tag
                return RedirectToAction(nameof(Index), new { eventId = eventTag.MoveeEventFrameId }); // Redirects to the index action with the event ID
            }
            return View(eventTag); // Returns the view with the model if the model state is invalid
        }

        // Displays the view for confirming the deletion of an event tag
        public IActionResult Delete(int id)
        {
            var currentUserId = _userManager.GetUserId(HttpContext.User); // Gets the current user's ID
            // Activates alarm sound for the current user
            ViewBag.Alarm = _alarmSoundRepository.ActivateSoundAlarm(currentUserId);
            var eventTag = (from et in _moveeEventTagRepository.GetAllMoveeEventTags() // Retrieves all event tags
                            where et.Id == id // Filters tags by the specified ID
                            select new MoveeEventTag // Selects relevant properties for the view
                            {
                                Id = et.Id,
                                MoveeEventFrameId = et.MoveeEventFrameId,
                                MoveeTagId = et.MoveeTagId,
                                TagName = (from u in _moveeEventTagRepository.GetMoveeTags() where u.Id == et.MoveeTagId select u.Name).FirstOrDefault()
                            }).SingleOrDefault(); // Ensures that only one event tag is returned

            return View(eventTag); // Returns the view for confirming the deletion of the event tag
        }

        // Handles the POST request to delete an event tag
        [HttpPost]
        [ActionName("Delete")] // Specifies that this method handles the "Delete" action
        public IActionResult DeleteEventTag(int id)
        {
            var userId = _userManager.GetUserId(HttpContext.User); // Gets the current user's ID
            DateTimeOffset now = DateTimeOffset.UtcNow; // Gets the current UTC time
            long unixTimeMilliseconds = now.ToUnixTimeMilliseconds(); // Converts the current time to Unix time in milliseconds

            var eventTag = _moveeEventTagRepository.GetAllMoveeEventTags().FirstOrDefault(a => a.Id == id); // Retrieves the event tag by ID
            _moveeEventTagRepository.RemoveMoveeEventTag(eventTag, userId, unixTimeMilliseconds); // Removes the event tag

            return RedirectToAction(nameof(Index), new { eventId = eventTag.MoveeEventFrameId }); // Redirects to the index action with the event ID
        }

        // Retrieves a list of tags for use in dropdowns or selections
        private List<SelectListItem> GetTags()
        {
            return _moveeEventTagRepository.GetMoveeTags().Select(c => new SelectListItem()
            {
                Value = c.Id.ToString(), // Sets the value attribute of the option

LoRinoBackend/Views/EventTag/Create.cshtml
@model MoveeEventTag
@{
    ViewData["Title"] = "Create";
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-route-eventId="@ViewBag.EventId" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MoveeEventFrameId" value="@ViewBag.EventId" />
            <div class="form-group">
                <label asp-for="MoveeTagId" class="control-label"></label>
                <select asp-for="MoveeTagId" class="form-control" asp-items="@ViewBag.Tags"></select>
                <span asp-validation-for="MoveeTagId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Stvori" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index" asp-route-eventId="@ViewBag.EventId">Natrag na popis</a>
</div>

@section Scripts {
    <script src="~/js/CustomScript.js"></script>
}

LoRinoBackend/Views/EventTag/Delete.cshtml
@model MoveeEventTag
@{
    ViewData["Title"] = "Delete";
}

<h2>Jeste li sigurni?</h2>

<p>
    @Model.TagName
</p>


<form asp-action="DeleteLocationUser">
    <input type="hidden" name="id" value="@Model.Id" />
    <input type="submit" value="Delete" class="btn btn-default" />
</form>
<a asp-action="Index" asp-route-id="@Model.MoveeEventFrameId">Natrag na popis</a>
@section Scripts {
    <script src="~/js/CustomScript.js"></script>
}

LoRinoBackend/Views/EventTag/Edit.cshtml
@model MoveeEventTag
@{
    ViewData["Title"] = "Edit";
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="MoveeEventFrameId" />
            <div class="form-group">
                <label asp-for="MoveeTagId" class="control-label"></label>
                <select asp-for="MoveeTagId" class="form-control" asp-items="@ViewBag.Tags"></select>
                <span asp-validation-for="MoveeTagId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Uredi" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-route-id="@Model.Id">Natrag na popis</a>
</div>

@section Scripts {
    <script src="~/js/CustomScript.js"></script>
}

LoRinoBackend/Views/EventTag/Index.cshtml
@model IEnumerable<MoveeEventTag>

@{
    ViewBag.Title = "Movee Tag";
    @ViewBag.CustomMessage}


<div class="row">
    <div class="col-12 mb-3 fa-pull-right">
        <a class="btn btn-default" style="width:auto"asp-controller="EventTag" asp-action="Create" asp-route-eventId="@ViewBag.EventId" >Dodijeli tag</a>
        <a class="btn btn-default" style="width:auto"asp-controller="MV" asp-action="AckMoveeEvent" asp-route-id="@ViewBag.EventId" >Nastavi sa potvrdom</a>
        <a class="btn btn-default" style="width:auto"asp-controller="MoveeTag" asp-action="Create">Stvori novi tag</a>
    </div>
</div>   

@if (Model.Any())
{
    <!-- Outer Row -->
    <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">
            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="p-5">
                                
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Tagovi</h1>
                                </div>
                                <div class="row justify-content-center">
                                    @foreach (var tag in Model)
                                    {
                                        
                                        <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                                            <div class="card shadow mb-4">
                                                <div class="card-body">

                                                    <h5 class="card-title">Naziv: @tag.TagName</h5>



                                                </div>
                                                <div class="card-footer">
                                                    <div class="align-self-center">
                                                    <form method="post" asp-action="Delete" asp-route-id="@tag.Id">
                                                        <a asp-controller="EventTag" asp-action="Edit" asp-route-id="@tag.Id" class="btn btn-default btn-sm">Uredi</a>
                                                        <span id="confirmDeleteSpan_@tag.Id" style="display:none">
                                                            <span>Jeste li sigurni?</span>
                                                            <button type="submit" class="btn btn-default btn-sm">Potvrdi</button>
                                                            <a href="#" class="btn btn-default btn-sm btn-sm"
                                                               onclick="confirmDelete('@tag.Id', false)">Odustani</a>
                                                        </span>

                                                        <span id="deleteSpan_@tag.Id">
                                                            <a href="#" class="btn btn-default btn-sm"
                                                               onclick="confirmDelete('@tag.Id', true)">Obriši</a>
                                                        </span>
                                                    </form>
                                                </div>
                                                </div>
                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

}
else
{
    <div class="row">
        <div class="card">
            <div class="card-header">
                Još nije dodjeljen niti jedan tag.
            </div>
            <div class="card-body">
                <h5 class="card-title">
                    Dodijeli novi tag pritiskom na gumb
                </h5>
                
            </div>
        </div>
    </div>

}
@section Scripts {
    <script src="~/js/CustomScript.js"></script>
}