LoRinoBackend/Models/Location.cs
// Import necessary namespaces
using System; // Provides fundamental classes and types
using System.Collections.Generic; // Provides classes for working with collections
using System.ComponentModel; // Provides classes for components and controls
using System.ComponentModel.DataAnnotations; // Provides attributes for validating data
using System.ComponentModel.DataAnnotations.Schema; // Provides attributes for mapping classes to database tables
using System.Linq; // Provides LINQ (Language Integrated Query) functionality
using System.Threading.Tasks; // Provides types for asynchronous programming

namespace LoRinoBackend.Models
{
    // Class representing a location in the system
    public class Location
    {
        // Unique identifier for the location
        public int Id { get; set; }

        // Name of the location with validation
        [Required, MaxLength(50, ErrorMessage = "Naziv lokacije ne smije biti duže od 50 slova")]
        [Display(Name = "Ime")]
        public string Name { get; set; }

        // Road name with validation
        [Display(Name = "Prometnica")]
        [Required]
        public string Road { get; set; }

        // Road section with validation
        [Display(Name = "Dionica")]
        [Required]
        public string RoadSection { get; set; }

        // Longitude of the location with formatting
        [Display(Name = "Geo. dužina")]
        [Required]
        [DisplayFormat(DataFormatString = "{0:N06}", ApplyFormatInEditMode = true)]
        public double Long { get; set; }

        // Latitude of the location with formatting
        [Display(Name = "Geo. širina")]
        [Required]
        [DisplayFormat(DataFormatString = "{0:N06}", ApplyFormatInEditMode = true)]
        public double Lat { get; set; }

        // Zoom level for the map view
        public double MapZoom { get; set; }

        // Minimum zoom level
        public double MinZoom { get; set; }

        // Maximum zoom level
        public double MaxZoom { get; set; }

        // Duration for event collection with validation
        [Display(Name = "Vrijeme sakupljanja")]
        [Range(1, 60, ErrorMessage = "Trajanje vremena sakupljanja događaja je maksimalno 60 sekundi")]
        [Required]
        public int TimerLenght { get; set; }

        // List of users associated with the location
        public List<LocationUser> LocationUserList { get; set; }

        // Foreign key for the associated company
        [Required]
        public int CompanyId { get; set; }

        // Reference to the associated company
        public Company Company { get; set; }

        // Default constructor initializing properties to default values
        public Location()
        {
            Id = 0;
            Name = null;
            Road = null;
            RoadSection = null;
            Long = 0;
            Lat = 0;
            MapZoom = 0;
            MinZoom = 0;
            MaxZoom = 0;
        }
    }
}

LoRinoBackend/ViewModels/LocationDetailsViewModel.cs
using LoRinoBackend.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LoRinoBackend.ViewModels
{
    public class LocationDetailsViewModel
    {
        public Location Location { get; set; }
        public IEnumerable<MoveeDataFrame> moveeDataFrames { get; set; }
        public List<MoveeEventFrame> moveeEventFrames { get; set; }
        public List<Device> Devices { get; set; }
        public MoveeEventFrame moveeEventFrame { get; set; }
        public int cntAlarm { get; set; }
        List<int> LocationIds { get; set; }
        public string PageTitle { get; set; }
    }
}

LoRinoBackend/ViewModels/LocationEditViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LoRinoBackend.ViewModels
{
    public class LocationEditViewModel : LocationCreateViewModel
    {
        public int Id { get; set; }
    }
}

LoRinoBackend/Controllers/LocationController.cs
using LoRinoBackend.Models; // Importing the necessary namespaces
using LoRinoBackend.ViewModels; // Importing view model classes
using Microsoft.AspNetCore.Authorization; // For authorization attributes
using Microsoft.AspNetCore.Hosting; // For accessing the web hosting environment
using Microsoft.AspNetCore.Identity; // For user identity management
using Microsoft.AspNetCore.Mvc; // For MVC controller functionality
using Microsoft.AspNetCore.Mvc.Rendering; // For select list functionalities
using Microsoft.EntityFrameworkCore; // For entity framework core functionalities
using System; // For general-purpose classes
using System.IO; // For file handling
using System.Linq; // For LINQ functionalities

namespace LoRinoBackend.Controllers // Defining the namespace for the controller
{
    public class LocationController : Controller // LocationController inherits from the base Controller class
    {
        // Dependencies for user management, repositories, and environment
        private readonly UserManager<ApplicationUser> userManager; // UserManager for managing user-related functionalities
        private readonly ICompanyRepository companyRepository; // Company repository for company-related data access
        private readonly ILocationRepository locationRepository; // Location repository for location-related data access
        private readonly IWebHostEnvironment hostingEnvironment; // Hosting environment for accessing web server environment
        private readonly IMoveeDataRepository moveeDataRepository; // Movee data repository for accessing Movee data
        private readonly IMoveeEventRepository moveeEventRepository; // Movee event repository for accessing Movee events
        private readonly IDeviceRepository deviceRepository; // Device repository for device-related data access
        private readonly IAlarmSoundRepository alarmSoundRepository; // Alarm sound repository for alarm sound functionalities

        // Constructor for dependency injection
        public LocationController(UserManager<ApplicationUser> userManager,
                                  ICompanyRepository companyRepository,
                                  IWebHostEnvironment hostingEnvironment,
                                  ILocationRepository locationRepository,
                                  IMoveeDataRepository moveeDataRepository,
                                  IMoveeEventRepository moveeEventRepository,
                                  IDeviceRepository deviceRepository,
                                  IAlarmSoundRepository alarmSoundRepository)
        {
            this.companyRepository = companyRepository; // Initializing the company repository
            this.locationRepository = locationRepository; // Initializing the location repository
            this.hostingEnvironment = hostingEnvironment; // Initializing the hosting environment
            this.moveeDataRepository = moveeDataRepository; // Initializing the Movee data repository
            this.moveeEventRepository = moveeEventRepository; // Initializing the Movee event repository
            this.deviceRepository = deviceRepository; // Initializing the device repository
            this.userManager = userManager; // Initializing the UserManager
            this.alarmSoundRepository = alarmSoundRepository; // Initializing the alarm sound repository
        }

        // Action method for displaying the Access Denied page
        [HttpGet] // HTTP GET method
        [AllowAnonymous] // Allows access to this method without authentication
        public IActionResult AccessDenied()
        {
            return View(); // Returns the AccessDenied view
        }

        // Action method for displaying the Not Found page
        [HttpGet] // HTTP GET method
        [AllowAnonymous] // Allows access to this method without authentication
        public IActionResult NotFound()
        {
            return View(); // Returns the NotFound view
        }

        // Action method for listing locations based on user role and company
        [HttpGet] // HTTP GET method
        [AllowAnonymous] // Allows access to this method without authentication
        public IActionResult ListLocations()
        {
            // Get the current user ID
            var userId = userManager.GetUserId(HttpContext.User); // Retrieves the current user's ID

            // Activate alarm sound based on user ID
            ViewBag.Alarm = alarmSoundRepository.ActivateSoundAlarm(userId); // Activates alarm sound for the user

            // Get the user details including their company
            ApplicationUser user = userManager.Users
                .Include(x => x.Company)
                .SingleOrDefaultAsync(x => x.Id == userId)
                .Result; // Retrieves the current user including company details

            // Retrieve locations associated with the current user
            var locationsByUser = locationRepository.GetLocationsByUserId(userId); // Retrieves locations associated with the current user

            // Check user roles to determine location access
            var isSuperAdmin = userManager.IsInRoleAsync(user, "Super Admin").Result; // Checks if the user is a Super Admin
            var isAdmin = userManager.IsInRoleAsync(user, "Admin").Result; // Checks if the user is an Admin
            var currentUserCompanyId = user.Company.Id; // Gets the user's company ID
            var sAdminLocations = locationRepository.GetAllLocations(); // Retrieves all locations for Super Admin
            var adminLocations = locationRepository.GetAllLocations().Where(a => a.CompanyId == currentUserCompanyId); // Retrieves locations for the user's company

            // Return different views based on user roles
            if (isSuperAdmin == true)
            {
                return View(sAdminLocations); // Returns all locations if Super Admin
            }
            if (isAdmin == true)
            {
                return View(adminLocations); // Returns company-specific locations if Admin
            }
            else if (locationsByUser == null)
            {
                return View("AccessDenied"); // Returns Access Denied view if no locations are found
            }
            else
            {
                return View(locationsByUser); // Returns locations associated with the user
            }
        }

        // GET action method for displaying the Create Location view
        [HttpGet] // HTTP GET method
        [Authorize(Policy = "SuperAdmin")] // Requires Super Admin role
        public IActionResult CreateLocation()
        {
            // Get the current user ID
            var userId = userManager.GetUserId(HttpContext.User); // Retrieves the current user's ID

            // Activate alarm sound based on user ID
            ViewBag.Alarm = alarmSoundRepository.ActivateSoundAlarm(userId); // Activates alarm sound for the user

            // Prepare the view model with available companies for dropdown list
            LocationCreateViewModel model = new LocationCreateViewModel();
            model.CompaniesDDL = locationRepository.GetAllCompanies()
                    .Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() })
                    .ToList(); // Populates the dropdown list with company names

            return View(model); // Returns the CreateLocation view with the model
        }

        // POST action method for handling the creation of a new location
        [HttpPost] // HTTP POST method
        [Authorize(Policy = "SuperAdmin")] // Requires Super Admin role
        public IActionResult CreateLocation(LocationCreateViewModel model)
        {
            if (ModelState.IsValid) // Checks if the model state is valid
            {
                // Create a new Location object from the model data
                Location newLocation = new Location
                {
                    Name = model.Name,
                    Road = model.Road,
                    RoadSection = model.RoadSection,
                    Long = model.Longitude,
                    Lat = model.Latitude,
                    TimerLenght = model.TimerLenght,
                    MapZoom = model.MapZoom,
                    CompanyId = model.CompanyId
                };

                // Add the new location to the repository
                locationRepository.Add(newLocation); // Adds the new location to the repository

                // Redirect to the location details page
                return RedirectToAction("LocationDetails", new { id = newLocation.Id }); // Redirects to the details of the newly created location
            }

            // Reload the companies dropdown list if model state is invalid
            model.CompaniesDDL = locationRepository.GetAllCompanies()
                    .Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() })
                    .ToList(); // Repopulates the dropdown list with company names

            return View(model); // Returns the CreateLocation view with the model
        }

        // GET action method for displaying location details
        [AllowAnonymous] // Allows access to this method without authentication
        public IActionResult LocationDetails(int id)
        {
            // Get the current user ID
            var userId = userManager.GetUserId(HttpContext.User); // Retrieves the current user's ID

            // Activate alarm sound based on user ID
            ViewBag.Alarm = alarmSoundRepository.ActivateSoundAlarm(userId); // Activates alarm sound for the user

            // Retrieve the location details
            Location location = locationRepository.GetLocation(id); // Retrieves the location details
            ApplicationUser user = userManager.Users
                .Include(x => x.Company)
                .SingleOrDefaultAsync(x => x.Id == userId)

LoRinoBackend/Views/Location/AccessDenied.cshtml
<div class="text-center">
    <h1 class="text-danger">Pristup odbijen</h1>
    <h6 class="text-danger">
       Nemate dopuštenje za izvršenje.
    </h6>
    <img src="~/images/access-denied.png" style="width:300px" />
</div>

LoRinoBackend/Views/Location/CreateLocation.cshtml
@model LocationCreateViewModel
@{ 
    ViewBag.Title = "Create Location"; 

}

<!-- Outer Row -->
<div class="row justify-content-center">

    <div class="col-xl-10 col-lg-12 col-md-9">
        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="p-5">
                            <div class="text-center">
                                <h4>Stvorite novu lokaciju</h4>
                            </div>
                            <form enctype="multipart/form-data" asp-controller="Location" asp-action="CreateLocation" method="post" class="mt-3">
                                @*<input type="hidden" asp-for="CompanyId" value="@Model.CompanyId" />*@
                                <div class="form-group row">
                                    <label asp-for="Name" class="col-sm-2 col-form-label">Naziv *</label>
                                    <div class="col-sm-10"><input class="form-control" asp-for="Name" placeholder="Naziv" /><span asp-validation-for="Name" class="text-danger"></span></div>
                                </div>
                                <div class="form-group row">
                                    <label asp-for="Road" class="col-sm-2 col-form-label">Prometnica *</label>
                                    <div class="col-sm-10"><input class="form-control" asp-for="Road" placeholder="Prometnica" /><span asp-validation-for="Road" class="text-danger"></span></div>
                                </div>
                                <div class="form-group row">
                                    <label asp-for="RoadSection" class="col-sm-2 col-form-label">Dionica *</label>
                                    <div class="col-sm-10"><input class="form-control" asp-for="RoadSection" placeholder="Dionica" /><span asp-validation-for="RoadSection" class="text-danger"></span></div>
                                </div>
                                <div class="form-group row">
                                    <label asp-for="TimerLenght" class="col-sm-2 col-form-label">Vrijeme sakupljanja alarma *</label>
                                    <div class="col-sm-10"><input class="form-control" asp-for="TimerLenght" placeholder="Vrijeme sakupljanja alarma u sekundama" /><span asp-validation-for="TimerLenght" class="text-danger"></span></div>
                                </div>

                                <div class="form-group row">

                                    <div class="col-6">
                                        <div class="form-group row">
                                            <div class="col-sm-4"></div>
                                            <div class="col-sm-8 text-info">Odaberi lokaciju klikom na kartu ili unesi kordinate</div>
                                        </div>
                                        <div class="form-group row">
                                            <label asp-for="Latitude" class="col-sm-4 col-form-label">Geo. širina *</label>
                                            <div class="col-sm-8"><input class="form-control" asp-for="Latitude" placeholder="Geo. širina" /><span asp-validation-for="Latitude" class="text-danger"></span></div>
                                        </div>
                                        <div class="form-group row">
                                            <label asp-for="Longitude" class="col-sm-4 col-form-label">Geo. dužina *</label>
                                            <div class="col-sm-8"><input class="form-control" asp-for="Longitude" placeholder="Geo. dužina" /><span asp-validation-for="Longitude" class="text-danger"></span></div>
                                        </div>
                                        <div class="form-group row">
                                            <label asp-for="MapZoom" class="col-sm-4 col-form-label">Zoom na karti *</label>
                                            <div class="col-sm-8"><input class="form-control" asp-for="MapZoom" placeholder="Prikaz zooma na karti" /><span asp-validation-for="MapZoom" class="text-danger"></span></div>
                                        </div>
                                        @if (User.IsInRole("Super Admin"))
                                        {
                                            <div class="form-group row">
                                                <label asp-for="Company.Name" class="col-sm-4 col-form-label">Naziv Tvrtke *</label>
                                                <div class="col-sm-8">
                                                    <select asp-for="CompanyId" class="custom-select mr-sm-2" asp-items="Model.CompaniesDDL"></select>
                                                    <span asp-validation-for="CompanyId" class="text-danger"></span>
                                                </div>
                                            </div>
                                        }
                                        
                                    </div>
                                    <div class="col-6">
                                        <div id="map" style="height : 250px; border: 1px solid grey"></div>
                                    </div>
                                </div>


                                <div lass="form-group row">
                                    <button class="btn btn-default" type="submit">Spremite </button>
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                </div>

                            </form>
                        </div>
                    </div>
                   
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles{
    <link rel="stylesheet" href="~/lib/leaflet/leaflet.css" />
    <link rel="stylesheet" href="~/lib/leaflet/Control.FullScreen.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-datepicker/css/bootstrap-datepicker.css" />
    <link rel="stylesheet" href="~/css/MarkerCluster.css" />
    <link rel="stylesheet" href="~/css/MarkerCluster.Default.css" />
    <style>
        #map {
            cursor: crosshair
        }
    </style>
}

@section Scripts {


    <script src="~/lib/leaflet/leaflet.js"></script>
    <script src="~/js/leaflet-color-markers.js"></script>
    <script src="~/js/CustomScript.js"></script>

    <script src="~/js/leaflet.markercluster-src.js"></script>
    <script src="~/lib/leaflet/Control.FullScreen.js"></script>

    <script src="~/lib/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>

    <script src="~/lib/bootstrap-datepicker/locales/bootstrap-datepicker.hr.min.js"></script>

    <script>

        var mapCenter = [45.767961, 15.941137];
        var mymap = L.map('map', {
            center: mapCenter,
            zoom: 6
        });


        L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
            attribution: 'Powered by <a href="http://www.microlink.hr" > Micro-Link</a>',
            maxZoom: 20,
            id: 'mapbox/streets-v11',
            tileSize: 512,
            zoomOffset: -1,
            accessToken: 'pk.eyJ1IjoianVrYTk3IiwiYSI6ImNrdTZxcng5eTN2c2IycHF0cnE1Zno5cHcifQ.gfrbRhNsX6XJOZywD-kSSw'
        }).addTo(mymap);

        L.control.fullscreen().addTo(mymap);

        var marker = L.marker(mapCenter).addTo(mymap);
        var updateMarker = function (lat, lng) {
            marker
                .setLatLng([lat, lng])
            //.bindPopup("Your location :  " + marker.getLatLng().toString())
            //.openPopup();
            return false;
        };

        mymap.on('click', function (e) {
            $('#Latitude').val(String(e.latlng.lat.toFixed(6)));
            $('#Longitude').val(String(e.latlng.lng.toFixed(6)));
            updateMarker(e.latlng.lat, e.latlng.lng);
        });

        mymap.on('zoomend', function () {

            $('#MapZoom').val(String(mymap.getZoom()));

        });



        var updateMarkerByInputs = function () {
            console.log($('#Long'), $('#Lat'));
            return updateMarker($('#Latitude').val(), $('#Longitude').val());
        }
        $('#Longitude').on('input', updateMarkerByInputs);
        $('#Latitude').on('input', updateMarkerByInputs);

       const zoomField = document.getElementById('MapZoom');


          // Add your map layers and other configurations here...

          // Set up an event listener for when the textbox value changes
          zoomField.addEventListener('input', function() {
            // Get the value from the textbox and parse it as a number
            var zoomValue = parseInt(zoomField.value);
            if (isNaN(zoomValue)) return; // Exit if the value is not a number

            // Check that the zoom value is within the valid range for your map
            const maxZoom = mymap.getMaxZoom();
            const minZoom = mymap.getMinZoom();
            if (zoomValue < minZoom || zoomValue > maxZoom) return;

            // Set the new zoom level and optionally animate the zoom
            mymap.flyTo(marker.getLatLng(), zoomValue, {
              duration: 1.5, // Animation duration in seconds
              easeLinearity: 0.5, // Animation smoothness
            });
          });


        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).next('.custom-file-label').html(fileName);
            });
        });

        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).next('.custom-file-label').html(fileName);
            });
        });

    </script>
}

LoRinoBackend/Views/Location/ListLocations.cshtml
@model IEnumerable<Location>

@{
    ViewBag.Title = "Lokacije";
    @ViewBag.CustomMessage
}

@if (User.IsInRole("Super Admin"))
        {
<p>
    <a class="btn btn-default" asp-action="CreateLocation">Stvori novu lokaciju</a>
</p>
        }
<br />

@if (Model.Any())
{
    <table class="table">
    <thead>
        <tr>
        @if (User.IsInRole("Super Admin"))
        {
            <th class="col-1">
                    @Html.DisplayNameFor(model => model.Id)
            </th>
        }
            <th class="col-2">
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th class="col-1">
                @Html.DisplayNameFor(model => model.Road)
            </th>
            <th class="col-2">
                @Html.DisplayNameFor(model => model.RoadSection)
            </th>
            <th class="col-1">
                @Html.DisplayNameFor(model => model.Long)
            </th>
            <th class="col-1">
                @Html.DisplayNameFor(model => model.Lat)
            </th>

                @if (User.IsInRole("Super Admin") || User.IsInRole("Admin"))
                {
            <th class="col-1">
                @Html.DisplayNameFor(model => model.TimerLenght)
            </th>
                }

                @if (User.IsInRole("Super Admin"))
                {
                    <th class="col-1">
                        @Html.DisplayNameFor(model => model.Company.Name)
                    </th>
                }

            <th class="col-1"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
            {
                <tr>
                    @if (User.IsInRole("Super Admin"))
                    {
                        <td>@Html.DisplayFor(modelItem => item.Id)</td>
                    }
                    <td><a asp-controller="Location" asp-action="LocationDetails" asp-route-id="@item.Id">@item.Name</a></td>
                    <td>@Html.DisplayFor(modelItem => item.Road)</td>
                    <td>@Html.DisplayFor(modelItem => item.RoadSection)</td>
                    <td>@Html.DisplayFor(modelItem => item.Long)</td>
                    <td>@Html.DisplayFor(modelItem => item.Lat)</td>
                    @if (User.IsInRole("Super Admin") || User.IsInRole("Admin"))
                    {
                        <td>@Html.DisplayFor(modelItem => item.TimerLenght)</td>
                    }
                    @if (User.IsInRole("Super Admin"))
                    {
                        <td>@Html.DisplayFor(modelItem => item.Company.Name)</td>
                    }
                    <td>
                        <form method="post" asp-action="LocationDelete" asp-route-id="@item.Id">
                            
                                @if (User.IsInRole("Super Admin"))
                                {
                                <div class="btn-group">
                                    <a asp-controller="Location" asp-action="LocationEdit" asp-route-id="@item.Id" class="btn btn-default">Uredi</a>
                                    <div>
                                        <span id="confirmDeleteSpan_@item.Id" style="display:none">
                                            <span>Jeste li sigurni?</span>
                                            <button type="submit" class="btn btn-default">Potvrdi</button>
                                            <a href="#" class="btn btn-default"
                                   onclick="confirmDelete('@item.Id', false)">Odustani</a>
                                        </span>

                                        <span id="deleteSpan_@item.Id">
                                            <a href="#" class="btn btn-default"
                                   onclick="confirmDelete('@item.Id', true)">Obriši</a>
                                        </span>
                                    </div>
                                </div>
                                }

                            
                        </form>

                    </td>
                </tr>
            
            }
        </tbody>
    </table>


}
else
{
    <div class="row">
        <div class="card">
            <div class="card-header">
                Još nije stvorena niti jedna lokacija.
            </div>
            @if (User.IsInRole("Super Admin"))
            {
                <div class="card-body">
                    <h5 class="card-title">
                    Stvori novu lokaciju pritiskom na gumb
                </h5>
                
            </div>
            }
        </div>
    </div>

}


@section Scripts {

    <script src="~/js/CustomScript.js"></script>
}
    

LoRinoBackend/Views/Location/NotFound.cshtml
<div class="text-center">
    <h1 class="text-danger">Pažnja</h1>
    <h6 class="text-danger">
       Lokacija nije pronađena.
    </h6>

</div>